[package]
name = "peripety"
version = "0.1.2"
authors = ["Gris Ge <fge@redhat.com>"]

[lib]
name = "peripety"
path = "lib.rs"

[dependencies]
sdjournal = { path = "../sdjournal" }
serde = "1"
serde_json = "1"
serde_derive = "1"
regex = "1"
libc = "0.2"
libmount = "0.1.10"
chrono = "0.4"
