[package]
name = "peripetyd"
version = "0.1.2"
authors = ["Gris Ge <fge@redhat.com>"]

[[bin]]
name = "peripetyd"
path = "main.rs"

[dependencies]
peripety = { path = "../peripety", version = "*"}
regex = ">=0.2"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
toml = ">=0.4"
